FROM python:3.11-slim

# Update the system
RUN apt update && apt upgrade -y


# Set the working directory
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY /src/auth /app/src/auth
COPY .env.auth /app/.env.auth
COPY requirements.txt /app/requirements.txt

# Install the dependencies
RUN pip install -r requirements.txt

# Expose the port
EXPOSE 8000

# Run the application
CMD ["uvicorn", "src.auth.main:app", "--host", "0.0.0.0", "--reload", "--port", "8000"]
